# v2 syntax
version: '2'

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=jarbas
      - POSTGRES_DB=jarbas

  app:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:80"
    ports:
      - 80
    links:
      - postgres
    depends_on:
      - postgres
