# v2 syntax
version: '2'

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=jarbas
      - POSTGRES_DB=jarbas

  app:
    build: .
    command: python jarbas/manage.py migrate && python jarbas/manage.py runserver 0.0.0.0:80
    environment:
      - SECRET_KEY=lets-rock
      - DATABASE_URL=postgres://jarbas:mysecretpassword@postgres:5432/jarbas
    ports:
      - 80
    links:
      - postgres
    depends_on:
      - postgres
